name: Continuous Integration
on:
  workflow_dispatch: 
    branches:
      - '2.2'
  push:
    branches:
      - '2.2'

  pull_request:
    branches:
      - '2.2'

  release:
    types: [ created ]

concurrency:
  group:  ci-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  compile-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
          architecture: x64

      - name: Compile
        shell: bash
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            compile

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: target-cache
          path: |
            ${{github.workspace}}/target
          if-no-files-found: error

  compile-linux-x86_64:
    needs: compile-java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: target-cache
          path: ${{github.workspace}}/target

      - name: Setup
        shell: bash
        run: |
          sudo apt-get update -m

          sudo apt-get install \
            libx11-dev:amd64 \
            libxtst-dev:amd64 \
            libxt-dev:amd64 \
            libxinerama-dev:amd64 \
            libx11-xcb-dev:amd64 \
            libxkbcommon-dev:amd64 \
            libxkbcommon-x11-dev:amd64 \
            libxkbfile-dev:amd64

      - name: Compile
        env:
          CC: x86_64-linux-gnu-gcc
          CFLAGS: '-O2 -march=x86-64 -mtune=generic -g -fomit-frame-pointer -flto -fno-stack-protector -pipe'
          LDFLAGS: '-fuse-ld=gold -Wl,-O1 -Wl,--as-needed'
          PKG_CONFIG_PATH: '/usr/lib/x86_64-linux-gnu/pkgconfig'
        shell: bash
        run: |
          mkdir -p target/build/libuiohook/
          cmake -B target/build/libuiohook/ -S src/external/libuiohook/ \
            -G "Unix Makefiles" \
            -D CMAKE_INSTALL_PREFIX=target/ \
            -D CMAKE_VERBOSE_MAKEFILE=ON \
            -D BUILD_SHARED_LIBS=OFF \
            -D USE_EPOCH_TIME=ON

          cmake --build target/build/libuiohook/ \
            --parallel 2 \
            --clean-first

          cmake --install target/build/libuiohook/

          mkdir -p target/build/jni/
          cmake -B target/build/jni/ \
            -G "Unix Makefiles" \
            -D CMAKE_PREFIX_PATH=target/ \
            -D CMAKE_SYSTEM_NAME=linux \
            -D CMAKE_SYSTEM_PROCESSOR=x86_64 \
            -D CMAKE_VERBOSE_MAKEFILE=ON

          cmake --build target/build/jni/ \
            --parallel 2 \
            --clean-first

          cmake --install target/build/jni/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: library-resources
          path: |
            ${{github.workspace}}/src/main/resources
          if-no-files-found: error

